[[bin]]
name = "energy-interactor"
path = "src/interact.rs"

[package]
name = "energy-interactor"
version = "0.0.0"
authors = [""]
edition = "2021"
publish = false

[dependencies]
toml = "0.8.6"

[dependencies.clap]
version = "4.4.7"
features = ["derive"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.multiversx-sc]
version = "=0.50.3"

[dependencies.multiversx-sc-modules]
version = "=0.50.3"

[dependencies.multiversx-sc-snippets]
version = "=0.50.3"

[dependencies.multiversx-sc-scenario]
version = "=0.50.3"

[dependencies.energy-interactor-proxies]
path = "proxies"

[dependencies.common_structs]
path = "../../common/common_structs"

# [dependencies.multisig]
# git = "https://github.com/multiversx/mx-contracts-rs/"
# rev = "747ba6f"

[dependencies.multisig]
path = "../multisig"

[dependencies.fees-collector]
path = "../fees-collector"

[dependencies.energy-factory]
path = "../../locked-asset/energy-factory"