multisig = "erd1qqqqqqqqqqqqqpgqhjcm5lqyasy5hdzgyhg5fc8vm6ejfpjh0n4s5euqfn"
energy_factory = "erd1qqqqqqqqqqqqqpgqfsdhdyyuyxlflc43axlvderg84ry7cfr0n4sf0nw6v"
fees_collector = "erd1qqqqqqqqqqqqqpgquq94exc0fs6x8tvzyzsmj2v643vmclct0n4shkztah"
